"""Explicit ORM model registration for standalone scripts.

The API imports routes that incidentally register every relationship target.
Standalone jobs must not rely on that import order: SQLAlchemy configures the
whole mapper registry on first query and otherwise fails only at runtime.
"""

from __future__ import annotations


def ensure_models_registered() -> None:
    from collegefootballfantasy_api.app.models import (  # noqa: F401
        application_instance,
        auth_action_token,
        auth_rate_limit_event,
        beta_access,
        chat,
        cfb_standing_snapshot,
        college_team,
        database_metadata,
        defense_rating,
        defense_vs_position,
        draft,
        draft_pick,
        game,
        game_odds,
        historical_stats,
        injury,
        injury_impact,
        league,
        league_invite,
        league_member,
        league_player_event,
        league_message,
        league_scoring_migration,
        league_settings,
        lineup_week_snapshot,
        matchup,
        mock_draft,
        mock_draft_pick,
        moderation_event,
        notification,
        player,
        player_game_stat,
        player_season_context,
        player_weekly_context,
        player_season_rank,
        player_stat,
        player_trade_value,
        player_availability_event,
        player_news_event,
        player_role_snapshot,
        player_week_score,
        player_waiver_availability,
        postseason,
        preseason_prior,
        provider_identity,
        provider_game_poll,
        provider_sync_state,
        projection_explanation,
        projection_input_audit,
        refresh_session,
        roster,
        scheduled_notification,
        scoring_admin_audit,
        scoring_run,
        saturday_pick,
        standing,
        team,
        team_environment,
        team_game_stat,
        team_schedule,
        team_season_rating,
        team_stats_snapshot,
        team_week_score,
        trade_offer,
        trade_offer_item,
        trade_review,
        transaction,
        usage_share,
        user,
        waiver_claim,
        waiver_claim_audit,
        waiver_priority,
        waiver_period,
        waiver_processing_run,
        watchlist,
        weekly_projection,
        worker_heartbeat,
    )
