from __future__ import annotations

import argparse
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = PROJECT_ROOT / "api" / "app" / "data" / "cfb27_ratings.json"
TARGET_PATH = PROJECT_ROOT / "web" / "client" / "lib" / "cfb27Ratings.ts"
VALID_POSITIONS = {"QB", "RB", "WR", "TE", "K"}


def _json_string(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_rating_rows(source_path: Path = SOURCE_PATH) -> list[tuple[int, str, str, str, int]]:
    source = json.loads(source_path.read_text(encoding="utf-8"))
    rows: list[tuple[int, str, str, str, int]] = []
    seen_keys: set[tuple[str, str, str]] = set()
    for index, row in enumerate(source, start=1):
        rank = int(row["rank"])
        name = str(row["name"]).strip()
        school = str(row["school"]).strip()
        position = str(row["position"]).strip().upper()
        overall = int(row["overall"])
        if not name or not school:
            raise ValueError(f"CFB27 row {index} is missing name or school")
        if position not in VALID_POSITIONS:
            raise ValueError(f"CFB27 row {index} has unsupported position {position!r}")
        if rank < 1:
            raise ValueError(f"CFB27 row {index} has invalid rank {rank}")
        if not 0 <= overall <= 99:
            raise ValueError(f"CFB27 row {index} has invalid overall {overall}")
        key = (name.lower(), school.lower(), position)
        if key in seen_keys:
            raise ValueError(f"Duplicate CFB27 identity in source: {name} / {school} / {position}")
        seen_keys.add(key)
        rows.append((rank, name, school, position, overall))
    return rows


def render_frontend_module(rows: list[tuple[int, str, str, str, int]]) -> str:
    row_lines = "\n".join(
        f"  [{rank}, {_json_string(name)}, {_json_string(school)}, {_json_string(position)}, {overall}],"
        for rank, name, school, position, overall in rows
    )
    return f"""// Generated by scripts/generate_cfb27_frontend.py from api/app/data/cfb27_ratings.json.
// Do not edit this file manually.

export type Cfb27Position = "QB" | "RB" | "WR" | "TE" | "K";

export type Cfb27Rating = {{
  rank: number;
  name: string;
  school: string;
  pos: Cfb27Position;
  ovr: number;
}};

const normalizeText = (value: string) =>
  value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/\\b(jr|jr\\.|iii|ii|iv)\\b/g, "")
    .replace(/[^a-z0-9]+/g, "")
    .trim();

const ratingRows = [
{row_lines}
] as const;

export const CFB27_RATINGS: Cfb27Rating[] = ratingRows.map(([rank, name, school, pos, ovr]) => ({{
  rank,
  name,
  school,
  pos,
  ovr,
}}));

const ratingByExactKey = new Map(
  CFB27_RATINGS.map((rating) => [
    `${{normalizeText(rating.name)}}|${{normalizeText(rating.school)}}|${{rating.pos}}`,
    rating,
  ])
);

const ratingsByNamePosition = CFB27_RATINGS.reduce((map, rating) => {{
  const key = `${{normalizeText(rating.name)}}|${{rating.pos}}`;
  map.set(key, [...(map.get(key) ?? []), rating]);
  return map;
}}, new Map<string, Cfb27Rating[]>());

export const findCfb27Rating = ({{
  name,
  school,
  pos,
}}: {{
  name: string;
  school: string;
  pos: string;
}}) => {{
  const normalizedPos = pos.toUpperCase();
  const exact = ratingByExactKey.get(
    `${{normalizeText(name)}}|${{normalizeText(school)}}|${{normalizedPos}}`
  );
  if (exact) return exact;

  const nameMatches = ratingsByNamePosition.get(`${{normalizeText(name)}}|${{normalizedPos}}`);
  return nameMatches?.length === 1 ? nameMatches[0] : null;
}};

export const getCfb27PositionPercentile = (rating: Cfb27Rating | null) => {{
  if (!rating) return 0.5;
  const samePosition = CFB27_RATINGS.filter((entry) => entry.pos === rating.pos);
  const ovrs = samePosition.map((entry) => entry.ovr);
  const min = Math.min(...ovrs);
  const max = Math.max(...ovrs);
  if (max === min) return 0.5;
  return (rating.ovr - min) / (max - min);
}};
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the frontend CFB27 ratings module from the backend JSON source of truth."
    )
    parser.add_argument("--check", action="store_true", help="Fail if the generated frontend file is stale.")
    args = parser.parse_args()

    rendered = render_frontend_module(load_rating_rows())
    if args.check:
        current = TARGET_PATH.read_text(encoding="utf-8") if TARGET_PATH.exists() else ""
        if current != rendered:
            raise SystemExit(
                f"{TARGET_PATH.relative_to(PROJECT_ROOT)} is stale. "
                "Run: PYTHONPATH=. uv run python scripts/generate_cfb27_frontend.py"
            )
        print(f"{TARGET_PATH.relative_to(PROJECT_ROOT)} is up to date.")
        return

    TARGET_PATH.write_text(rendered, encoding="utf-8")
    print(f"Generated {TARGET_PATH.relative_to(PROJECT_ROOT)} from {SOURCE_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
