[[pages]]
path = "app.py"
name = "Home"

[[pages]]
path = "pages/1_Leagues.py"
name = "Leagues"

[[pages]]
path = "pages/2_Teams.py"
name = "Teams"

[[pages]]
path = "pages/3_Rosters.py"
name = "Rosters"

[[pages]]
path = "pages/4_Players.py"
name = "Players"

[[pages]]
path = "pages/7_Projections_Ranking.py"
name = "Projections Ranking"

[[pages]]
path = "pages/5_Draft.py"
name = "Draft"

[[pages]]
path = "pages/6_Matchup.py"
name = "Matchup"
